### ISSUE TITLE
TEROS Pipeline - review request

### ISSUE THREAD

**Issue by ahopple** [COMPASS-DOE/TEMPEST#23]
Hi @bpbond
 
Could you review the updates to the TEROS pipeline? I've tagged you with BBL where I had questions. Thank you!

**Comment by bpbond** [comment]
Notes
* We're going to need to think about data sizes. The `teros_data` object is already 130 MB. I did some work to trim it down.
* NA plot rows—this is happening just because the data files have `Data_Logger_ID` / `Data_Table_ID` combinations that aren't in the map file:

![na](https://user-images.githubusercontent.com/1956468/111850433-ae1e2980-88e6-11eb-8a63-4d4d06f54883.png)

Related question for @ahopple : why do we have both "TEMPEST_TEROS_12_location_and_ID.csv" (in `Design_Map/`) and "TEMPEST_TEROS_Network_Location&ID.csv" (in `Raw_Data/`)?

**Comment by bpbond** [comment]
Re above: for example cataloguer ID 41 doesn't have any entries for data table IDs 12, 13, and 17-22.

**Comment by bpbond** [comment]
```
# BBL what are your thoughts on data cleaning? I'm hopeful that we won't have to deal with these
# large value jumps often now that we have fixed most of the TEROS network issues. For now, I am identifying
# the faulty sensors as those with values 2 ST DEV outside of the mean and removing them. We might want to use a
# moving average or something similar to identify sensor errors down the road.
```
I would suggest we produce a report for how many values are removed, by sensor and day perhaps.

For filtering, we don't want to do this:
```r
teros_data2 %>%
  filter(...
```
...because the whole row will get removed if even one of TSOIL, VWC, or EC is bad. Also we don't want to use a standard deviation-based criterion, as that's very sensitive to outliers; using the mean absolute deviation is [better](https://core.ac.uk/download/pdf/206095228.pdf).

**Comment by bpbond** [comment]
@ahopple opening PR with some suggested changes.

**Comment by bpbond** [comment]
>Calculating daily averages - or do we want to keep the 15-minute data, BBL?

Good question. For QA/QC I think daily data are generally going to be much more useful, although obviously we want to keep the 15-minute data available for anyone who wants it.

**Comment by bpbond** [comment]
@ahopple I have changed the raw data plotting in the PR to group by datalogger—thoughts?

![tsoil](https://user-images.githubusercontent.com/1956468/111866993-962ac200-8947-11eb-95e1-cab8a40cc055.png)
