### ISSUE TITLE
SP Week of May 17

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/TEMPEST#38]
## TEMPEST
- [x] Use function we wrote to read in all loggers
- [x] Merge with `ports.csv` to link to tree codes / plots
- [x] QA/QC: look for problems with that merge (missing tree codes, logger codes etc.)
- [x] QA/QC: flag out of bounds - negative values and values over 1.0
- [x] Email Roy for his sapflow troubleshooting process and updates

## ESS-DIVE
- [x] If we have consensus on term format, update terms

**Comment by bpbond** [comment]
@stephpenn1 so writing another paper is something you'd like to do. 👍  Here are some possibilities to think about, and we can discuss further:

* Restart the [Rs-Js work](https://github.com/PNNL-PREMIS/PREMIS-sapflow). I guess the analysis is 80% done here, but it is a little tricky because there are lots of different angles (as you know).
* Lead the [first synthesis paper](https://github.com/COMPASS-DOE/COMPASS-synthesis). I think the analytical work is 50% done here, but I would heavily take charge of that—or work in concert with you. It would be focused and tight, focusing on the meta-analysis of three separate response variables for water addition and separation.
* Something like [fortedata](https://github.com/FoRTExperiment/fortedata)! For example, build a `compassdata` package and a companion Shiny data dashboard, and write a paper describing them, kind of like Jeff's paper.
